apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: linguabot
build:
  artifacts:
  - image: gcr.io/PROJECT_ID/linguabot
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/*.yml
profiles:
- name: dev
  build:
    local:
      push: false
  deploy:
    kubectl:
      flags:
        global: ["--namespace=default"]
- name: prod
  build:
    googleCloudBuild:
      projectId: PROJECT_ID
  deploy:
    kubectl:
      flags:
        global: ["--namespace=production"]